### ISSUE TITLE
Error message about "Expected all tensors to be on the same device"

### ISSUE THREAD

**Issue by JIN-Li-stats** [czifan/DeepSurv.pytorch#8]
An error occurred when I ran the code with 
```
python main.py
```
The error message is as follows

> Running Simulated Linear(linear.ini)...
=> load 4000 samples
=> load 1000 samples
Traceback (most recent call last):
  File "d:/Desktop/DeepSurv.pytorch/main.py", line 109, in <module>
    best_c_index = train(os.path.join(configs_dir, ini_file))
  File "d:/Desktop/DeepSurv.pytorch/main.py", line 54, in train
    risk_pred = model(X)
  File "C:\Miniconda3\envs\deep\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "d:\Desktop\DeepSurv.pytorch\networks.py", line 64, in forward
    return self.model(X)
  File "C:\Miniconda3\envs\deep\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Miniconda3\envs\deep\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Miniconda3\envs\deep\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Miniconda3\envs\deep\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)

I don't know whether the version of the packages causes it. The version of Python and packages I used are as follows
- Python 3.8
- torch = 1.12.1
- prettytable = 3.5.0
- numpy = 1.23.3
- lifelines = 0.27.1
- pandas = 1.5.0
- h5py = 3.7.0

**Comment by CQTsang** [comment]
I encounter the same problem. I check the requirement.txt in this code and I find the torch the code used is only for cpu. I guess that's the reason why.

**Comment by CQTsang** [comment]
i've checked out the problem.
In main.py, add
`X = X.to(device)
 y = y.to(device)
 e = e.to(device)`
in line 53 and line 68, in which we extract X, y, e in train_loader and the test_loader

meanwhile, you should add
 `mask = mask.cuda()`
in Line8 in networks.py , which is in method forward of class NegativeLogLikelihood . 

By adding these to cuda, you can run your code on gpu.

**Comment by czifan** [comment]
Hi, the solution indicated by CQTsang can solve this problem. Thanks for CQTsang!
